### ISSUE TITLE
SoapySDR fails to install following Python 3.8 update

### ISSUE THREAD

**Issue by orryverducci** [pothosware/homebrew-pothos#41]
In the last few days the Homebrew formula for Python has been updated to use Python 3.8 (it was previously Python 3.7).

This change has broken building SoapySDR, so installing it using `brew install soapysdr` now fails with the following error:

```
==> Installing soapysdr from pothosware/pothos
==> Downloading https://github.com/pothosware/SoapySDR/archive/soapy-sdr-0.7.2.t
==> Downloading from https://codeload.github.com/pothosware/SoapySDR/tar.gz/soap
######################################################################## 100.0%
==> Installing pothosware/pothos/soapysdr
==> cmake .. -DENABLE_PYTHON=OFF -DENABLE_PYTHON3=ON -DSOAPY_SDR_EXTVER=release 
==> make install
Last 15 lines from /Users/Orry/Library/Logs/Homebrew/soapysdr/02.make:
      _wrap_SwigPyIterator_incr(_object*, _object*) in SoapySDRPYTHON_wrap.cxx.o
      _wrap_SwigPyIterator_decr(_object*, _object*) in SoapySDRPYTHON_wrap.cxx.o
      _wrap_SwigPyIterator_next(_object*, _object*) in SoapySDRPYTHON_wrap.cxx.o
      ...
  "__Py_NotImplementedStruct", referenced from:
      _wrap_SwigPyIterator___eq__(_object*, _object*) in SoapySDRPYTHON_wrap.cxx.o
      _wrap_SwigPyIterator___ne__(_object*, _object*) in SoapySDRPYTHON_wrap.cxx.o
      _wrap_SwigPyIterator___add__(_object*, _object*) in SoapySDRPYTHON_wrap.cxx.o
      _wrap_SwigPyIterator___sub__(_object*, _object*) in SoapySDRPYTHON_wrap.cxx.o
      SwigPyObject_richcompare(SwigPyObject*, SwigPyObject*, int) in SoapySDRPYTHON_wrap.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [python3/_SoapySDR.so] Error 1
make[1]: *** [python3/CMakeFiles/_SoapySDR3.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):

  https://github.com/pothosware/homebrew-pothos/issues

The command "brew install soapysdr" failed and exited with 1 during .
```

**Comment by guruofquality** [comment]
python3.8 links differently, i think in this case it wants `-undefined dynamic_lookup`

**Comment by guruofquality** [comment]
I pushed a flag change to master

**Comment by cortices** [comment]
Confirmed this fixed the issue as shown in #40. Should be able to close this.

**Comment by guruofquality** [comment]
thanks!

**Comment by orryverducci** [comment]
Thanks for fixing.

As Homebrew by default installs from the latest release, which doesn't contain this fix (and therefore still fails), should I change my build script which depends on SoapySDR to use `--head`, or is there any plan for a new release soon?
